baseline:
  input_dim: 4
  seq_len: 129
  num_classes: 1
  num_channels: 100
  dropout: 0.5
  lr: 0.0001
  epochs: 50
  patience: 5
  save_path: './models/best_model.pt'
  device: 'cuda'
  batch_size: 64
  trade_off_trsr: 1
  loss_fn: 'focal'
  optimizer: 'adam'
  dropout_rate: 0.1
transyn:
  epochs: 50
  patience: 5
  save_path: './models/best_model.pt'
  device: 'cuda'
  lr: 0.00038089211244930033
  trade_off_trsr: 1
  batch_size: 32
  optimizer: 'adam'
  loss_fn: 'focal'
  bio_hidden: 128
  dropout_rate: 0.3
  head_hidden: 64